server:
  port: 20001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


#db
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:       # password is null
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: svc-provider
  jpa:
    database: MYSQL  # Specify the DBMS
    show-sql: true # Show or not log for each sql query



## mybatis
mybatis:
  mapper-locations: classpath*:/mybatis-mapping/*Mapper.xml
#  config-locations: classpath*:/mybatis-config.xml


